server:
  port : 8901
spring:
  application:
    name: client-01
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: yeyi
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/      #注册中心的地址
      # 注册到Eureka的注册中心
    register-with-eureka: true
      # 获取注册实例列表
    fetch-registry: true
management:
  security:
    enabled: false
