server:
  port: 8900   #(指定应用端口)
spring:
  application:
    name: eureka-server #声明本服务在注册中心展示的名字、也是在网关访问时定位服务的名字
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己作为服务注册到注册中心，默认为true，false不能将自己注册到自己,
    #如果有多个服务注册中心的微服务的话，可以将这个设置为true，表示可以将注册中心1注册到注册中心2中
    #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表。
    #如果是服务注册中心集群，需要开启，开启就是去掉该配置，采用默认配置即可
    fetch-registry: false  #表示是否从eureka注册中心中获取注册信息,默认为true

    #注册中心的交互地址，设置多个地址可以用,分隔  查询服务和注册服务都需要依赖这个地址
    #关于设置注册中心这么关键的服务，如果是单点话，遇到故障就是毁灭性的。
    #在一个分布式系统中，服务注册中心是最重要的基础部分，理应随时处于可以提供服务的状态。为了维持其可用性，使用集群是很好的解决方案
    #所以 在一个分布式系统中，设置最少两个服务注册中心是最基本的
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
